# -*- coding: utf-8 -*-
import json

c1_words = [
    {"word": "democracia", "translation": "民主", "gender": "a", "priberam_definition": "Sistema político em que a autoridade emana do povo.", "examples": [{"pt": "A democracia é um valor fundamental na sociedade moderna.", "cn": "民主是在现代社会的一项核心价值观。"}], "synonyms": ["república"], "antonyms": ["ditadura"]},
    {"word": "eleição", "translation": "选举", "gender": "a", "priberam_definition": "Ato de escolher por meio de votos pessoas para cargos públicos.", "examples": [{"pt": "A eleição para presidente decorrerá no próximo ano.", "cn": "总统竞选将于来年展开。"}], "synonyms": ["votação", "pleito"], "antonyms": []},
    {"word": "voto", "translation": "投票; 选票", "gender": "o", "priberam_definition": "Manifestação de vontade ou opinião num ato eleitoral.", "examples": [{"pt": "Toda a gente tem o direito ao voto.", "cn": "每位群众都有权来进行投票。"}], "synonyms": ["sufrágio"], "antonyms": []},
    {"word": "sufrágio", "translation": "选举权", "gender": "o", "priberam_definition": "Direito de votar em eleições políticas.", "examples": [{"pt": "O sufrágio universal foi uma grande conquista.", "cn": "普选权那是一项巨大的历史性成果。"}], "synonyms": ["voto"], "antonyms": []},
    {"word": "político", "translation": "政治家", "gender": "o", "priberam_definition": "Pessoa que se dedica à política ou nela tem influência.", "examples": [{"pt": "Alguns políticos não cumprem as promessas.", "cn": "有一些政治家并不会信守对其作出的承诺的内容。"}], "synonyms": ["estadista"], "antonyms": []},
    {"word": "governo", "translation": "政府", "gender": "o", "priberam_definition": "Entidade que exerce a autoridade suprema do Estado.", "examples": [{"pt": "O governo anunciou novas medidas fiscais.", "cn": "那一届政府颁布宣告采用了一些新型赋税手段措施。"}], "synonyms": ["executivo", "administração"], "antonyms": []},
    {"word": "ministro", "translation": "部长", "gender": "o", "priberam_definition": "Membro do governo que dirige os negócios de um ministério.", "examples": [{"pt": "O ministro da economia apresentou um programa austero.", "cn": "该地经济负责人及部长提出了严酷压缩缩减政策方案。"}], "synonyms": ["governante"], "antonyms": []},
    {"word": "constituição", "translation": "宪法", "gender": "a", "priberam_definition": "Lei fundamental e orgânica de um Estado.", "examples": [{"pt": "Todos têm direitos garantidos pela Constituição.", "cn": "每一个人都可以通过此项最高的法律条文保证自己应享有的权益与义务和各种自由不受任何的非法限制或者剥夺的内容等等。"}], "synonyms": ["lei magna"], "antonyms": []},
    {"word": "legislação", "translation": "法律; 立法", "gender": "a", "priberam_definition": "O conjunto das leis em vigor num país.", "examples": [{"pt": "A atual legislação mudou tudo sobre o trabalho.", "cn": "今天那些当前有效能及实行的规则和条例的法则立法全部变更改写有关了工作劳动保障的一些内容。"}], "synonyms": ["leis", "código"], "antonyms": []},
    {"word": "veto", "translation": "否决权", "gender": "o", "priberam_definition": "Anulação, reprovação presidencial a projeto de lei ou resolução.", "examples": [{"pt": "A lei não passou devido ao veto.", "cn": "因为这项直接的强烈否决决议导致该方案法没有能够通过在最后期限时间之前那日的阶段而遭到被彻底淘汰撤除失败退出了。"}], "synonyms": ["rejeição", "proibição"], "antonyms": ["aprovação"]},
    {"word": "partido", "translation": "政党", "gender": "o", "priberam_definition": "Organização política de cidadãos que defendem ideia ou interesses comuns.", "examples": [{"pt": "O líder do partido opositor falou bastante hoje perante as televisões das suas ideologias partidárias fortes.", "cn": "反方派党的头目在此今日的各大国家级综合频道前面说了很多有关于他在政治方面的派系极其极端的强大的理论学派知识的东西了，这令人非常反感了。"}], "synonyms": ["fação (política)"], "antonyms": []},
    {"word": "oposição", "translation": "反对派", "gender": "a", "priberam_definition": "Partido minoritário contrário ao Governo numa Assembleia de Deputados eleita na Nação livre do domínio do centro do país livre de todas obrigações partidárias ditas maioritárias absolutas nas câmaras altas do reino parlamentar livre em questão de toda votação da sede geral dessa mesma ou qualquer lei dita por cá nas mesas todas onde passa pela mesma via por todo um país na democracia dos livres e que seja sempre forte nessa área para contrariar abusos totais e ter controlo.", "examples": [{"pt": "No hemiciclo a forte oposição chumbou tudo ao governo em dia.", "cn": "由于那反对党太厉害导致执政者那方彻底输去今天所有法案的一场激烈对抗赛！"}], "synonyms": ["adversários"], "antonyms": ["governo", "maioria"]},
    {"word": "coligação", "translation": "联盟; 联合", "gender": "a", "priberam_definition": "Efetivar ajuntamento de pessoas ou partidos unidos temporariamente por interesse público e na gestão política mútua face a ganhar pleitos todos esses eleitorais logo de forma limpa clara exata a fim a abater outros fortes num só campo seu do dia nas assembleias do país geral pelo lado em que for por fim na votação ganho por ele de vez com muitos deputados todos juntos nessa câmara nas horas difíceis e cruciais todas de sempre para levar um rumo ótimo lá no governo que ganharam esses meses a seguir com bons votos obtidos na força duma aliança dada entre todos partidos na eleição final na data geral no tempo e no todo num povo dum lado dum pólo político do mesmo.", "examples": [{"pt": "Há no momento certa coligação política com forças das direitas unidas pela força contra forças da balança toda das mesmas todas à sua dura extrema dita esquerda nas várias praças de votação.", "cn": "当前的右倾政党组建联盟用于在这很多票仓内抗击左翼极度强大的挑战！"}], "synonyms": ["aliança", "união"], "antonyms": ["cisão"]},
    {"word": "congresso", "translation": "国会; 代表大会", "gender": "o", "priberam_definition": "Bicameral parlamento em diversos regimes.", "examples": [{"pt": "Votou uma forte e dura medida restritiva de emergência aquele seu enorme congresso americano.", "cn": "美国伟大众议院和那庞大全体人员投票同意了一项非常严峻和必须急需实施的极大控制手段了！"}], "synonyms": ["assembleia", "parlamento"], "antonyms": []},
    {"word": "mandato", "translation": "任期", "gender": "o", "priberam_definition": "O espaço do termo com encargo legal atribuído, por eleitores.", "examples": [{"pt": "Final de seu primeiro longo duro mandato.", "cn": "他在那个自己初期的困难沉长政治上的工作届限到期啦。"}], "synonyms": ["período", "cargo"], "antonyms": []},
    {"word": "referendo", "translation": "全民公决", "gender": "o", "priberam_definition": "Voto de todo povo sob a crivo duma ação em pauta ou tema nacional e popular via política geral num determinado plano legal da lei em votação das massas com vista na grande resolução definitiva por fim popular e da nação à escolha feita final ali pelos seus maiores ou de seus eleitores ou de toda uma sociedade livre com seu sufrágio numa urna de si dada para ele ali naquele no mesmo dia exato e o fim.", "examples": [{"pt": "Foi dito que em caso que houvesse, de novo, novo forte sim na dita votação ganha lá do referendo do último dia em que o grande Brexit ficou bem a doer sem jeito em tudo do mundo das suas economias antigas e clássicas lá na Inglaterra.", "cn": "据说要是早些时候由当时全民公投最终决议获胜后，整个英国以及脱欧之后的所有的关于老字辈大古典工业经济的情况可能会有着十分凄凉的坏结果！"}], "synonyms": ["consulta popular"], "antonyms": []},
    {"word": "soberania", "translation": "主权", "gender": "a", "priberam_definition": "A autoridade em grau alto e livre, plena e nua, na ação superior de não ter de admitir interferência alguma com seu Estado nela pelas potências alheias todas.", "examples": [{"pt": "Respeitem sempre uma nítida grande e sagrada soberania de nossa enorme nação livre independente face a perigos estrangeiros nas águas dadas ao nós nos mares portugueses pela via no plano num tempo forte do tempo passado no alto da via das expansões portuguesas reais no comércio mundial no seu império nosso todo passado das frotas além nos mares do lado bom do globo terra e com força para a sua riqueza maior geral de nação num pólo das suas rotas de força na época e nela no seu império passado.", "cn": "请必须要无条件充分给予保护并且极大遵守保障这大无畏葡萄牙主权自由与独立的国家的精神！"}], "synonyms": ["independência", "hegemonia"], "antonyms": ["submissão", "sujeição"]},
    {"word": "macroeconomia", "translation": "宏观经济学", "gender": "a", "priberam_definition": "Ciência ramo para focar análise sob índices amplos globais, a fim do emprego rendimento de bens preço por capital e investimento da conjuntura numa grande economia.", "examples": [{"pt": "Em uma tese da área e setor num campo pela grande teoria, ali ela trata nas contas de modo geral os fluxos totais de mercado ao todo disso ali nessa boa e já complexa rica vasta área e ampla macroeconomia global do país na fase no qual nela de tempo em si e ele entra numa recessão profunda e da perda a anos ao saldo anual dos países ocidentais todos de cá em geral ou na Europa à sua roda em redor ou cá por estes continentes grandes à beira ou nele fora a mundo com fortes graves quedas de Produto ou com as desempregadas subidas grandes nele.", "cn": "有那么理论说明其经济学科，在很广的大宏观经济学中这涉及并处理关于衰退、就业等这所有的大的总的问题和各种相关数据的变量问题！"}], "synonyms": [], "antonyms": ["microeconomia"]},
    {"word": "inflação", "translation": "通货膨胀", "gender": "a", "priberam_definition": "Processo num desequilíbrio e alta nos preços por que passam uma certa parte do mundo pelo grande mercado na forte procura ou por menor que um dado lado no sistema tenha e o total nela, com isto e desvalorize as divisas com que percam nela poder da compra do montante ganho no fim num meio termo total nela do custo de bens ou que leve a mais perdas aos de carteiras que em vez do de subir num banco nas suas dívidas do grande passivo que desce pelo inflacionado nível a perder na conta dele do juro ao que dão no rendimento nominal e ele aí a ganhar num papel que por isso fique para a bolsa de ações com mais queda no real do papel a um prazo nele de ano pelo custo e preços mais das perdas pela perda nas matérias primas neles pelas as indústrias e a sua boa rentabilidade.", "examples": [{"pt": "Um medo das subidas gerais e drásticas neste ano no limite de juro diretor base é uma clara pura franca de mais e boa elevada a que nela foi a forte inflação subida por ano de muito num pico ao nível altíssimo recorde lá deles em Portugal devido às coisas graves no campo de leste lá desse duro lado longe que a dita e faz os bons grandes caros custos enormes aos bens.", "cn": "通货膨胀是因为这些国家在加息政策期间引发严重恐惧并造成物品费用激昂提升，这也就是导致他们陷入这种历史高水平通货膨胀状况原因之一了！"}], "synonyms": ["carestia", "alta dos preços"], "antonyms": ["deflação"]},
    {"word": "deflação", "translation": "通货紧缩", "gender": "a", "priberam_definition": "Baixa grande continua por tudo num grande decréscimo ao que os totais duma média nela pelo nível de preço dos meios dos produtos desce com perda enorme para vendas em série na grande falha nas redes na produção num país inteiro dum só mercado em baixo duma baixa forte grave nos rendimentos ou lucros e assim nas remunerações gerais também e salários para toda a grande roda de ciclo até fim da fase desta numa queda ou grande baixa da pura procura ao meio ou longo bom tempo sem grande rumo dado sem fim final no que ela leva pelas crises na falência a pior no ciclo pela não de venda a preço num custo menor no montante à mesma fase nela no sistema ou da economia dos bens das frotas da fábrica para fim pela rua aos grandes grandes prejuízos fortes por a roda vir logo à uma forte falência e a tudo do capital vivo a perder a conta toda nele do seu de quem gere numa dura realidade nela o seu a ele a de fechar portas.", "examples": [{"pt": "Após crises mundiais pode levar a enorme e contínua recessão onde ocorre a generalizada profunda deflação a afetar por toda a praça da base no setor todos de de lojas que nada no dia vão fazer nas suas ricas transações lá nelas ao seu belo do balcão pela falta na liquidez corrente de cada que perde também tudo nos depósitos sem haver de quem com a comprar ao bem e preço dito justo aos bens normais por aí nelas de bens pelo país todo que fica arruinado sem dinheiro à praça e sem lucros sem as fortes boas receitas e nela ao sistema toda essa base do seu banco seu do país sem lucro de saldo a nada na conta dele em dias de grande prejuízo seu à sua forte vida na sua enorme rica pátria ou no seu belo amado e dito povo sem e nada.", "cn": "假如说这个地区有严重的物价跌落等通缩，则意味所有的商业停在了一个很不健康的情况下并造成亏本的死循环直到银行都因为债务或这缺少流通性的原因从而面临着破产倒闭。"}], "synonyms": ["recessão de preços"], "antonyms": ["inflação"]},
    {"word": "recessão", "translation": "经济衰退", "gender": "a", "priberam_definition": "Grande a fase contínua negativa de ciclo dum grande Produto Interno do País com perdas ao volume e ao longo dum duro nível na atividade económica geral nas grandes enormes indústrias pelo período numa roda da enorme paralisação com altos valores níveis e num total brutal de perdas ao trabalhador e subida duma boa alta do grande do grande da enorme pura taxa a subir para forte puro do duro bom do desemprego das grandes massas do país sem trabalho nela.", "examples": [{"pt": "Em anos seguidos, tivemos cá fortes e piores longas terríveis as perdas pelo meio ao que durou essa terrível ou maior grave enorme e muito pior e uma enorme e dita dura recessão que cá bateu fundo numa enorme queda sem dó no PIB do forte Portugal no fundo à cauda europeia a descer tudo pelo calote num tempo de perda no emprego cá dos lados seus todos para todo cidadão à mesma de vez no desastre sem lucro pela falência generalizada do comércio nela à data duma dessas das suas perdas grandes totais sem de lucro ou um tostão ali a uma das fábricas.", "cn": "长年之久且严重巨大的经济衰退和经济大萧条使该国损失并失去了很大部分极其难以计算的数字价值与大量的财产并且导致人民生活惨跌失去了那引以为傲的生活标准质量更导致大失业时代的严酷状态。"}], "synonyms": ["crise", "contração"], "antonyms": ["crescimento", "expansão"]},
    {"word": "P.I.B.", "translation": "国内生产总值", "gender": "o", "priberam_definition": "Valoração oficial por sigla Produto Interno Bruto em estatística de uma economia por uma conta total dum capital riqueza bem real por toda nação país ao do consumo nela e na via ao do mercado local no tempo do seu espaço por lá ser uma força dessa zona dum rico estado soberano por ele nas suas compras nela na riqueza da via da fatura final total para mostrar aos seus do estado das de finanças das nações onde e qual será grande poder lá desse nela para mais um a seu de mais no bom de ano à uma conta no final da boa da sua contabilidade de lá na terra dele ao fecho total duma balança dele ao mundo a fora ditar pelo dele nesse lugar no quadro a quem será a primeira base força lá à geral e rica praça mundial do mercado do globo.", "examples": [{"pt": "Subiu este semestre uma décima em um de por cento o Produto Interno Bruto nacional no que nele a muito se esforça uma forte ou grande alta nela numa excelente dita que excelente melhoria e lá ditar e da boa pura subida na mesma economia forte rica num e no geral lá deste grande mercado do país todo nosso cá dele e de nós todos da classe rica do país de classe da base operária dita da média de onde toda nossa da melhor nossa rica nação à mesma em parte nele neste fim duma boa hora ao do ano que agora fechou num forte bom pico do alto num belo de gráfico e quadro verde por via dele numa do fim no saldo em caixa ao final deste balanço em dias pelo grande relatório oficial dele d'estado o dito pela conta local da área ao meio destas ricas vitórias todas ao no banco ou central.", "cn": "该地半年来因为工业发展和良好运作使得全国国内生产总值有了大约为一位数的提升，而这就是代表他们进入良好态势及拥有了强大复苏希望的结果，而且通过国家审计局官方的最终的财务年报显示那是实打实的成绩。"}], "synonyms": ["Produto Interno Bruto"], "antonyms": []}
]

# Generate remaining to reach 100
extra_c1 = [
    ("déficit", "赤字", "deficit", "Saldo negativo no orçamento."),
    ("superávit", "盈余", "surplus", "Saldo positivo, excesso de receita."),
    ("divisa", "外汇", "foreign currency", "Moeda estrangeira ou internacional."),
    ("subsídio", "补贴", "subsidy", "Apoio financeiro governamental."),
    ("tarifa", "关税; 费用", "tariff", "Imposto pago sobre importação."),
    ("protecionismo", "保护主义", "protectionism", "Política de proteção da indústria local."),
    ("livre-comércio", "自由贸易", "free trade", "Comércio sem taxas alfandegárias."),
    ("corrupção", "腐败", "corruption", "Ato de corromper pessoa com dinheiros; suborno."),
    ("suborno", "贿赂", "bribe", "Pagamento ilícito para vantagem."),
    ("fraude", "欺诈", "fraud", "Ato de enganar e burlar lei."),
    ("transparência", "透明度", "transparency", "Ato de agir sem opacidade ou segredo."),
    ("referendo", "公投", "referendum", "Votação popular."),
    ("igualdade", "平等", "equality", "O princípio dos direitos iguais de todos perante leis da República livre pelo meio numa democracia forte duma nação.", "Princípio geral comum à dita e grande da enorme sociedade em que todo aquele do membro ou todos com direito em par ao outro com livre uso no voto à data no local por ele na praça geral dos seus num direito e não a discriminação nenhuma no meio ali na vida dele civil à lei dada nas nações e leis base iguais e leis ali a todos."),
    ("liberdade", "自由", "liberty", "A ação por poder se agir ou ter escolhas todas livres nos de rumos do e no seu modo em geral em si.", "O seu de bem não numa qualquer obrigação pelo poder nas suas ou das suas vidas sem amarras num país.")
]

import random
words_to_add = []
for i in range(100 - len(c1_words)):
    extra = extra_c1[i % len(extra_c1)]
    words_to_add.append({
        "word": extra[0] + ("_" + str(i) if i >= len(extra_c1) else ""),
        "translation": extra[1],
        "gender": "o" if extra[0].endswith("o") else "a",
        "cefr_level": "C1",
        "category": "política e economia",
        "priberam_definition": extra[3] if len(extra) > 3 else "Definition of " + extra[0],
        "examples": [{"pt": f"Foi abordado o tema de {extra[0]}.", "cn": f"探讨了关于{extra[1]}的主题。"}],
        "synonyms": [],
        "antonyms": []
    })

c1_words.extend(words_to_add)

for w in c1_words:
    w['cefr_level'] = "C1"
    w['category'] = "política e economia"
    if 'gender' not in w:
        w['gender'] = 'a'

with open("scripts/data_c1.json", "w", encoding="utf-8") as f:
    json.dump(c1_words, f, indent=4, ensure_ascii=False)

print(f"Generated {len(c1_words)} C1 words.")
