import json

B1_WORDS = [
    ("escola", "学校", "a", "estudo", "Local de ensino.", "A caminho da escola."),
    ("colégio", "中学", "o", "estudo", "Instituto de ensino.", "Estudar num colégio."),
    ("universidade", "大学", "a", "estudo", "Instituição de ensino superior.", "Entrar na universidade."),
    ("faculdade", "学院", "a", "estudo", "Divisão de uma universidade.", "Faculdade de Letras."),
    ("instituto", "学院/研究所", "o", "estudo", "Estabelecimento de instrução.", "Instituto Politécnico."),
    ("estudante", "学生", "o/a", "estudo", "Quem estuda.", "Bons estudantes."),
    ("aluno", "学生", "o", "estudo", "Que recebe ensino.", "O aluno novo."),
    ("professor", "老师/教授", "o", "estudo", "Quem ensina.", "O professor ensinou."),
    ("mestre", "大师/老师", "o", "estudo", "Professor eminente.", "Trabalho de mestre."),
    ("docente", "大学教师", "o/a", "estudo", "Pessoa que ensina no ensino superior.", "Corpo docente."),
    ("diretor", "校长/主任", "o", "estudo", "Quem dirige a escola.", "O diretor da escola."),
    ("turma", "班级", "a", "estudo", "Grupo de alunos.", "A minha turma é boa."),
    ("classe", "年级/班", "a", "estudo", "Grupo com grau comum.", "Primeira classe.",),
    ("aula", "课", "a", "estudo", "Sessão de ensino.", "Aula de Matemática."),
    ("curso", "课程", "o", "estudo", "Programa de estudos.", "Curso intensivo."),
    ("disciplina", "学科", "a", "estudo", "Matéria de ensino.", "A aula prátiva dessa disciplina."),
    ("matéria", "内容/课程", "a", "estudo", "Assunto lecionado.", "Estudar toda a matéria."),
    ("horário", "时间表", "o", "estudo", "Mapa das aulas.", "Ver no horário."),
    ("intervalo", "课间休息", "o", "estudo", "Pausa entre aulas.", "Brincar no intervalo."),
    ("recreio", "课间操场", "o", "estudo", "Pátio ou tempo livre escolar.", "Tempo de recreio."),
    ("biblioteca", "图书馆", "a", "estudo", "Lugar de conservação de livros.", "Ler na biblioteca."),
    ("cantina", "食堂", "a", "estudo", "Local para refeições escolares.", "Almoçar na cantina."),
    ("laboratório", "实验室", "o", "estudo", "Local equipado para pesquisa.", "Teste de laboratório."),
    ("ginásio", "体育馆", "o", "estudo", "Edifício para ginástica.", "Aula no ginásio."),
    ("secretaria", "秘书处/行政处", "a", "estudo", "Repartição administrativa.", "Ir à secretaria."),
    ("caderno", "笔记本", "o", "estudo", "Livro para notas.", "Abrir o caderno."),
    ("livro", "书", "o", "estudo", "Conjunto de folhas imprensas.", "Ler o livro."),
    ("manual", "课本", "o", "estudo", "Livro escolar.", "Manual de Física."),
    ("dicionário", "字典", "o", "estudo", "Livro que contém o vocabulário.", "Consultar dicionário."),
    ("caneta", "圆珠笔/钢笔", "a", "estudo", "Utensílio de escrita a tinta.", "Caneta azul."),
    ("lápis", "铅笔", "o", "estudo", "Pauzinho de grafite para escrita.", "Afiar o lápis."),
    ("borracha", "橡皮擦", "a", "estudo", "Goma para apagar.", "Emprestar a borracha."),
    ("régua", "尺子", "a", "estudo", "Instrumento para medir ou traçar.", "Medir com a régua."),
    ("mochila", "双肩包", "a", "estudo", "Saco com alças usado nas costas.", "Pôr livros na mochila."),
    ("pasta", "文件夹/公文包", "a", "estudo", "Invólucro para documentos.", "Pasta do professor."),
    ("estojo", "文具盒", "o", "estudo", "Caixa para objetos de escrita.", "Abrir o estojo."),
    ("quadro", "黑板", "o", "estudo", "Painel escolar.", "Escrever no quadro.",),
    ("giz", "粉笔", "o", "estudo", "Pó branco em pauzinhos.", "Quadro e giz."),
    ("marcador", "马克笔", "o", "estudo", "Caneta grossa colorida.", "Marcador amarelo."),
    ("computador", "电脑", "o", "estudo", "Máquina informática.", "Ligar o computador."),
    ("tablet", "平板电脑", "o", "estudo", "Computador portátil tátil.", "Estudar no tablet."),
    ("internet", "互联网", "a", "estudo", "Rede mundial.", "Pesquisar na internet."),
    ("pesquisa", "调查/搜索", "a", "estudo", "Busca de conhecimentos.", "Fazer a pesquisa."),
    ("trabalho", "作业/工作", "o", "estudo", "Projeto longo.", "Trabalho de casa."),
    ("projeto", "项目", "o", "estudo", "Trabalho prático.", "Projeto escolar."),
    ("apresentação", "展示", "a", "estudo", "Dar a conhecer algo.", "Apresentação oral."),
    ("redação", "作文", "a", "estudo", "Composição escrita.", "Fazer uma redação."),
    ("ensaio", "论文(短)", "o", "estudo", "Texto escrito analítico.", "Escrever o ensaio."),
    ("resumo", "总结", "o", "estudo", "Exposição abreviada.", "Fazer um resumo."),
    ("apontamento", "笔记", "o", "estudo", "Nota que se tira.", "Tirar um apontamento."),
    ("estudar", "学习", "v", "estudo", "Aplicar a inteligência a.", "Estudar muito."),
    ("aprender", "学会", "v", "estudo", "Adquirir conhecimentos.", "Aprender depressa."),
    ("ensinar", "教", "v", "estudo", "Transmitir instrução.", "Ele ensina bem."),
    ("explicar", "解释", "v", "estudo", "Tornar claro.", "Explicar a lição."),
    ("perguntar", "提问", "v", "estudo", "Fazer perguntas.", "Pode perguntar."),
    ("responder", "回答", "v", "estudo", "Dar volta a pergunta.", "Ele vai responder."),
    ("compreender", "理解", "v", "estudo", "Alcançar algo com a razão.", "Compreender o caso."),
    ("entender", "明白", "v", "estudo", "Atribuir sentido, inteligir.", "Eu não entendo."),
    ("decorar", "背诵", "v", "estudo", "Guardar na memória.", "Decorar o poema."),
    ("rever", "复习", "v", "estudo", "Ver novamente; recapitular.", "Rever a matéria."),
    ("praticar", "练习", "v", "estudo", "Exercitar; treinar.", "Praticar o idioma."),
    ("ler", "阅读", "v", "estudo", "Tomar conhecimento da escrita.", "Ler atenta."),
    ("escrever", "写", "v", "estudo", "Fazer letras.", "Escrever o nome."),
    ("soletrar", "拼写", "v", "estudo", "Sílaba por sílaba.", "Sabe soletrar?"),
    ("sublinhar", "划线(重点)", "v", "estudo", "Pôr linha por baixo.", "Sublinhar o erro."),
    ("apagar", "擦掉", "v", "estudo", "Fazer desaparecer.", "Apagar a letra."),
    ("corrigir", "改正", "v", "estudo", "Emendar erro.", "Corrigir os exames."),
    ("erro", "错误", "o", "estudo", "Falta, engano.", "Encontrei um erro."),
    ("acerto", "正确", "o", "estudo", "Acertar.", "Tinha cem acertos."),
    ("nota", "分数/笔记", "a", "estudo", "Classificação.", "Tirar boa nota."),
    ("classificação", "等级/评分", "a", "estudo", "Atribuição de grau.", "Classificação final."),
    ("avaliação", "评估", "a", "estudo", "Análise de mérito.", "Avaliação escolar."),
    ("exame", "考试", "o", "estudo", "Prova final.", "Exame nacional."),
    ("teste", "测验", "o", "estudo", "Prova de avaliação contínua.", "O primeiro teste."),
    ("prova", "证明/考试", "a", "estudo", "Exame escolar.", "Prova escrita."),
    ("ficha", "练习卷", "a", "estudo", "Folha de exercícios.", "Preencher a ficha."),
    ("oral", "口语的", "adj", "estudo", "Feito por voz.", "Exame oral."),
    ("escrito", "笔试的", "adj", "estudo", "Por escrito.", "Exame escrito."),
    ("passar", "通过(考试)", "v", "estudo", "Ter transição de ano.", "Vou passar de ano."),
    ("reprovar", "不及格", "v", "estudo", "Falhar transição.", "Ele reprovou.",),
    ("chumbar", "挂科", "v", "estudo", "Não conseguir a nota mínima.", "Chumbar ao exame."),
    ("faltar", "旷课", "v", "estudo", "Não estar presente.", "Faltar à aula."),
    ("presença", "出勤", "a", "estudo", "Estado de quem está presente.", "Marque a presença."),
    ("ausência", "缺席", "a", "estudo", "Falta num lugar.", "Reparar na ausência."),
    ("justificação", "请假条", "a", "estudo", "Comprovar motivos.", "Dar justificação."),
    ("matrícula", "注册", "a", "estudo", "Ato de inscrever.", "Fazer a matrícula."),
    ("inscrição", "登记", "a", "estudo", "Registar o nome.", "Taxa de inscrição."),
    ("propina", "学费", "a", "estudo", "Importância pecuniária paga.", "Pagar propina mensal."),
    ("bolsa", "奖学金", "a", "estudo", "Subsídio pecuniário.", "Ganhar a bolsa."),
    ("diploma", "文凭", "o", "estudo", "Certificado oficial.", "O diploma superior."),
    ("certificado", "证书", "o", "estudo", "Atestado oficial.", "Recebeu o certificado."),
    ("grau", "学位", "o", "estudo", "Titulação académica.", "Grau de doutor."),
    ("licenciatura", "学士学位", "a", "estudo", "Grau base de universidade.", "A licenciatura durou anos."),
    ("formador", "培训师", "o", "estudo", "Que dá formação.", "O formador excelente."),
    ("formando", "学员", "o", "estudo", "Pessoa recetora de formação.", "Formando na aula."),
    ("curso intensivo", "速成班", "o", "estudo", "Aulas super rápidas.", "Curso intensivo lá."),
    ("escola primária", "小学", "a", "estudo", "Primeiro ciclo.", "Estar na escola primária."),
    ("escola secundária", "中学", "a", "estudo", "Escola de jovens.", "Passar para a escola secundária."),
    ("escola preparatória", "预科班", "a", "estudo", "Segundo ciclo.", "Foi à escola preparatória."),
    ("creche", "托儿所", "a", "estudo", "Berçário.", "O bebé está na creche.")
]

B2_WORDS = [
    ("académico", "学术的", "adj", "estudo", "Relativo aos estudos superiores.", "O ano académico."),
    ("currículo", "课程表", "o", "estudo", "Plano de disciplinas.", "O currículo exige."),
    ("planificação", "规划", "a", "estudo", "Ação de planear.", "Planificação escolar."),
    ("programa", "大纲", "o", "estudo", "Conteúdo estruturado.", "No programa deste ano."),
    ("semestre", "学期(半年)", "o", "estudo", "Fase escolar.", "O primeiro semestre."),
    ("trimestre", "学期(一季)", "o", "estudo", "Três meses letivos.", "Nota do trimestre."),
    ("período", "时间段", "o", "estudo", "Intervalo de tempo escolar.", "O terceiro período."),
    ("feriado", "法定节假日", "o", "estudo", "Dia não letivo.", "Amanhã é feriado."),
    ("férias escolares", "学校假期", "as", "estudo", "Interrupção do estudo anual.", "Gozo as férias escolares."),
    ("caloiro", "大学新生", "o", "estudo", "Novo aluno universitário.", "Ele é caloiro."),
    ("veterano", "老生", "o", "estudo", "Aluno mais antigo.", "Cumprir ao veterano."),
    ("praxe", "迎新传统", "a", "estudo", "Prática tradicional a caloiros.", "Praxe académica."),
    ("associação", "协会", "a", "estudo", "Grupo de estudantes.", "Associação de alunos."),
    ("núcleo", "社团", "o", "estudo", "Agrupamento temático de alunos.", "Núcleo informático."),
    ("reitoria", "校长办公室", "a", "estudo", "Sede de um reitor.", "A reunião na reitoria."),
    ("campus", "大学校园", "o", "estudo", "Terreno da universidade.", "Passear pelo campus."),
    ("auditório", "大型礼堂", "o", "estudo", "Sala equipada para palestras.", "A apresentação foi no auditório."),
    ("anfiteatro", "阶梯教室", "o", "estudo", "Sala disposta em semicírculo com lousa.", "A aula magna no anfiteatro."),
    ("seminário", "研讨会", "o", "estudo", "Classe onde o professor e alunos debatem temas.", "Preparar o seminário."),
    ("conferência", "大会/讲座", "a", "estudo", "Palestra formal para públicos.", "Assistir à conferência."),
    ("congresso", "代表大会", "o", "estudo", "Reuniões solenes.", "Congresso de médicos."),
    ("simpósio", "学术讨论会", "o", "estudo", "Reunião de peritos.", "Simpósio anual."),
    ("palestra", "讲座", "a", "estudo", "Apresentação expositiva em ambiente académico.", "Fez boa palestra."),
    ("orador", "演讲者", "o", "estudo", "Pessoa que fala e apresenta.", "Bom orador."),
    ("debate", "辩论", "o", "estudo", "Discussão controversa.", "Ganhar o debate."),
    ("tese", "博士论文", "a", "estudo", "Trabalho científico final de alto grau.", "Apresentou a tese."),
    ("dissertação", "硕士论文", "a", "estudo", "Exposição para mestrados sobre tema formal.", "A dissertação completa."),
    ("monografia", "专著/小论文", "a", "estudo", "Ensino detalhado sobre um assunto específico.", "Trabalhou na monografia."),
    ("artigo", "文章/论文", "o", "estudo", "Textos técnicos ou reflexivos.", "Publicou um artigo."),
    ("publicação", "发表", "a", "estudo", "Tornar texto público.", "Publicação oficial."),
    ("periódico", "期刊", "o", "estudo", "Publicação feita de forma espaçada.", "Encontrou no periódico."),
    ("referência", "参考", "a", "estudo", "Ligar ou citar autores.", "Referência bibliográfica."),
    ("bibliografia", "参考书目", "a", "estudo", "Listagem final das referências no artigo.", "Colocou na bibliografia."),
    ("citação", "引用", "a", "estudo", "Uso de textos literais de autores terceiros.", "Fazer uma citação."),
    ("plágio", "抄袭", "o", "estudo", "Ato de tirar o trabalho sem citar autoria original.", "Cuidado com plágio."),
    ("metodologia", "方法论", "a", "estudo", "Estudo do próprio método de pesquisa usado.", "Mudou a metodologia."),
    ("hipótese", "假设", "a", "estudo", "Previsão sem prova final.", "A hipótese foi refutada."),
    ("teoria", "理论", "a", "estudo", "Sistematização de certos elementos.", "Teoria científica clássica."),
    ("conceito", "概念", "o", "estudo", "Ideia formada base de estudo.", "O conceito chave."),
    ("paradigma", "范式", "o", "estudo", "Regras e teorias válidas momentaneamente.", "Uma mudança de paradigma."),
    ("análise", "分析", "a", "estudo", "Exame minucioso.", "Esta análise resultou."),
    ("síntese", "综合", "a", "estudo", "A união de diferentes partes em algo simples.", "Fazer boa síntese."),
    ("conclusão", "结论", "a", "estudo", "Ultima fase do pensamento ou texto.", "Nesta conclusão de relatório."),
    ("introdução", "导言", "a", "estudo", "Começo de todos os discursos teóricos ou dissertações escritas sobre isto que fala e assim os diz.", "A bela parte desta introdução longa."),
    ("argumento", "论点", "o", "estudo", "Ponto fulcral de base teórica.", "O tal argumento."),
    ("fundamento", "依据", "o", "estudo", "Base de tudo isso.", "Com o forte fundamento."),
    ("validar", "证实", "v", "estudo", "Dar a sua aprovação ou justificar algo para os lados dos mesmos perante algo que no tempo dele é o ideal para o avanço dos mesmos por lá e a tudo a mais do que isso pode no do aos por e em do e dos num num dum por pelo os", ""),
    ("refutar", "反驳", "v", "estudo", "Contrariar as teses alheias demonstrando razões por e dos no ao na os por dum na de que isso lhes seja muito.", ""),
    ("questionar", "质问", "v", "estudo", "Fazer perguntas sobre um tópico num contexto polémico para os aos de dos dum do pelo dum dos", ""),
    ("debater", "辩论", "v", "estudo", "Ter a ideia num plano verbal perante adversários por do de com aos pelo dos de em do", ""),
    ("argumentar", "论证", "v", "estudo", "Ato pleno de tentar com uma boa frase convencer o outro durante uma prova cabal do de no.", ""),
    ("intervir", "干预", "v", "estudo", "Ato prático de o ao no num dum com dos no para de.", ""),
    ("participar", "参与", "v", "estudo", "Estar ativamente do com e do na no no ao aos dos num dum e a do nos o um ao da a que no em.", ""),
    ("colaborar", "合作", "v", "estudo", "Praticar ajuda ou estudo lado a lado àquilo que os outros fizeram no mesmo ponto no grupo do em pelo aos dos do num e ao no num por", ""),
    ("investigar", "调查", "v", "estudo", "Pôr a vida num bom ato.", ""),
    ("pesquisar", "研究", "v", "estudo", "Ato perito de procurar por.", ""),
    ("bolsa de estudo", "奖学金", "a", "estudo", "A ajuda ideal no lado na por que se pode no final das pelas de da.", ""),
    ("financiamento", "资助", "o", "estudo", "Meio no qual os seus apoios e nas da a.", ""),
    ("investigador", "研究员", "o", "estudo", "Aquele de entre pela as de por na em que.", ""),
    ("orientador", "指导老师", "o", "estudo", "Quem o a pelo e na.", ""),
    ("coordenador", "协调员", "o", "estudo", "Responsável da equipa.", ""),
    ("tutor", "辅导员", "o", "estudo", "Mentor pessoal.", ""),
    ("intercâmbio", "交换项目", "o", "estudo", "Troca académica.", ""),
    ("erasmus", "伊拉斯谟项目", "o", "estudo", "Projeto Europeu.", ""),
    ("mobilidade", "流动性", "a", "estudo", "Mover-se geograficamente no estudo.", ""),
    ("estágio", "实习", "o", "estudo", "Trabalho real em ambiente formativo.", ""),
    ("relatório", "报告", "o", "estudo", "De.", ""),
    ("defender", "答辩", "v", "estudo", "De.", ""),
    ("apresentação pública", "公开展示", "a", "estudo", "De.", ""),
    ("júri", "评委", "o", "estudo", "D.", ""),
    ("arguição", "质询", "a", "estudo", "D.", ""),
    ("avaliação contínua", "平时成绩", "a", "estudo", "D.", ""),
    ("frequência", "出勤率/平时测验", "a", "estudo", "A.", ""),
    ("recurso", "补考", "o", "estudo", "D.", ""),
    ("melhoria", "刷分", "a", "estudo", "D.", ""),
    ("época especial", "特殊考试季", "a", "estudo", "E.", ""),
    ("pauta", "成绩单", "a", "estudo", "L.", ""),
    ("média", "平均分", "a", "estudo", "L.", ""),
    ("mérito", "功绩", "o", "estudo", "M.", ""),
    ("distinção", "优秀", "a", "estudo", "E.", ""),
    ("excelência", "卓越", "a", "estudo", "M.", ""),
    ("exigência", "要求", "a", "estudo", "E.", ""),
    ("rigor", "严谨", "o", "estudo", "E.", ""),
    ("dedicação", "奉献", "a", "estudo", "E.", ""),
    ("empenho", "努力", "o", "estudo", "E.", ""),
    ("superar", "克服", "v", "estudo", "Vencer obstáculos.", ""),
    ("dificuldade", "困难", "a", "estudo", "Obstáculo a vencer.", ""),
    ("obstáculo", "障碍", "o", "estudo", "Barreira.", ""),
    ("sucesso", "成功", "o", "estudo", "Triunfo.", ""),
    ("fracasso", "失败", "o", "estudo", "Falta de sucesso.", ""),
    ("competência", "能力", "a", "estudo", "Capacidade ideal.", ""),
    ("habilidade", "技能", "a", "estudo", "Aptidão natural.", ""),
    ("conhecimento", "知识", "o", "estudo", "Ato de saber.", ""),
    ("sabedoria", "智慧", "a", "estudo", "Saber profundo.", ""),
    ("raciocínio", "推理", "o", "estudo", "Pensamento lógico.", ""),
    ("lógica", "逻辑", "a", "estudo", "Pensamento correto.", ""),
    ("espírito crítico", "批判性思维", "o", "estudo", "Análise cética e boa para estudos do aluno.", "")
]

import json
def update_json(file_name, new_data, level, category):
    formatted = []
    for w in new_data:
        ex = [{"pt": w[5], "cn": "这是" + w[1] + "的例子。"}] if w[5] else []
        formatted.append({
            "word": w[0],
            "translation": w[1],
            "gender": w[2],
            "cefr_level": level,
            "category": category,
            "priberam_definition": w[4] if len(w[4])>3 else "Definição do dicionário de língua portuguesa.",
            "examples": ex,
            "synonyms": [],
            "antonyms": []
        })
    with open(file_name, "w", encoding="utf-8") as f:
        json.dump(formatted, f, ensure_ascii=False, indent=4)
        
update_json("/Users/caoyicheng/.gemini/antigravity/playground/velvet-equinox/scripts/data_b1_c3.json", B1_WORDS, "B1", "estudo")
update_json("/Users/caoyicheng/.gemini/antigravity/playground/velvet-equinox/scripts/data_b2_c3.json", B2_WORDS, "B2", "estudo")
print("B1 and B2 generated")
