import json
import os

A1_WORDS = [
    ("loja", "商店", "a", "compras e lazer", "Estabelecimento comercial.", "Eu vou à loja."),
    ("mercado", "市场", "o", "compras e lazer", "Lugar onde se compra e vende.", "Feira no mercado."),
    ("supermercado", "超市", "o", "compras e lazer", "Grande mercado com autosserviço.", "Compras no supermercado."),
    ("padaria", "面包店", "a", "compras e lazer", "Loja que vende pão.", "Pão fresco na padaria."),
    ("talho", "肉店", "o", "compras e lazer", "Loja onde se vende carne.", "Comprar bifes no talho."),
    ("farmácia", "药店", "a", "compras e lazer", "Estabelecimento onde se vendem medicamentos.", "Comprar remédios na farmácia."),
    ("dinheiro", "钱", "o", "compras e lazer", "Moeda de troca.", "Não tenho dinheiro."),
    ("caixa", "收银台", "a", "compras e lazer", "Local de pagamento.", "Pagar na caixa."),
    ("preço", "价格", "o", "compras e lazer", "Valor em dinheiro.", "Qual é o preço?"),
    ("barato", "便宜的", "adj", "compras e lazer", "Que custa pouco.", "É muito barato."),
    ("caro", "昂贵的", "adj", "compras e lazer", "Que custa muito.", "Demasiado caro."),
    ("comprar", "买", "v", "compras e lazer", "Adquirir com dinheiro.", "Quero comprar isto."),
    ("vender", "卖", "v", "compras e lazer", "Ceder por preço.", "Eles vão vender a casa."),
    ("pagar", "支付", "v", "compras e lazer", "Dar dinheiro em troca.", "Pagar a conta."),
    ("troco", "找零", "o", "compras e lazer", "Dinheiro devolvido.", "Fique com o troco."),
    ("multibanco", "ATM机/刷卡机", "o", "compras e lazer", "Máquina bancária.", "Pagar com multibanco."),
    ("recibo", "收据", "o", "compras e lazer", "Comprovante de pagamento.", "Aqui está o recibo."),
    ("saco", "袋子", "o", "compras e lazer", "Recipiente de plástico ou papel.", "Precisa de saco?"),
    ("produto", "产品", "o", "compras e lazer", "Bem produzido ou vendido.", "Bom produto."),
    ("promoção", "促销", "a", "compras e lazer", "Venda a preço reduzido.", "Está em promoção."),
    ("desconto", "折扣", "o", "compras e lazer", "Redução do preço.", "Tem desconto."),
    ("roupa", "衣服", "a", "compras e lazer", "Vestuário geral.", "Lavar a roupa."),
    ("sapato", "鞋子", "o", "compras e lazer", "Calçado exterior.", "Sapato preto."),
    ("calças", "裤子", "as", "compras e lazer", "Roupa para as pernas.", "Vestir calças."),
    ("camisa", "衬衫", "a", "compras e lazer", "Peça de vestir com botões.", "Camisa branca."),
    ("camisola", "毛衣/卫衣", "a", "compras e lazer", "Vestuário de malha.", "Camisola quente."),
    ("casaco", "外套", "o", "compras e lazer", "Roupa de agasalho.", "Vestir o casaco."),
    ("vestido", "连衣裙", "o", "compras e lazer", "Peça feminina inteira.", "Vestido longo."),
    ("saia", "裙子", "a", "compras e lazer", "Peça feminina até certas alturas.", "Saia curta."),
    ("chapéu", "帽子", "o", "compras e lazer", "Cobertura para a cabeça.", "Pôr o chapéu."),
    ("mala", "包/行李箱", "a", "compras e lazer", "Objeto para levar coisas.", "Levar a mala."),
    ("tamanho", "尺码", "o", "compras e lazer", "Dimensão da roupa.", "Qual é o tamanho?"),
    ("número", "尺码(鞋)", "o", "compras e lazer", "Medida do sapato.", "Número 40."),
    ("cor", "颜色", "a", "compras e lazer", "Sensação visual.", "Que cor prefere?"),
    ("provador", "试衣间", "o", "compras e lazer", "Tenda para experimentar roupa.", "Onde é o provador?"),
    ("cinema", "电影院", "o", "compras e lazer", "Local para ver filmes.", "Vamos ao cinema."),
    ("filme", "电影", "o", "compras e lazer", "Obra cinematográfica.", "Ver um filme."),
    ("bilhete", "票", "o", "compras e lazer", "Entrada paga.", "Comprar bilhete."),
    ("pipocas", "爆米花", "as", "compras e lazer", "Milho rebentado.", "Gosto de pipocas."),
    ("teatro", "剧院", "o", "compras e lazer", "Local de atuações.", "Peça de teatro."),
    ("parque", "公园", "o", "compras e lazer", "Espaço verde público.", "Passear no parque."),
    ("jardim", "花园", "o", "compras e lazer", "Terreno com plantas cultivadas.", "Jardim botânico."),
    ("praia", "海滩", "a", "compras e lazer", "Margem cheia de areia.", "Vamos à praia."),
    ("piscina", "游泳池", "a", "compras e lazer", "Tanque de água para nadar.", "Nadar na piscina."),
    ("museu", "博物馆", "o", "compras e lazer", "Local de arte e história.", "Visitar o museu."),
    ("concerto", "音乐会", "o", "compras e lazer", "Atuação musical.", "O concerto foi bom."),
    ("música", "音乐", "a", "compras e lazer", "Arte dos sons.", "Ouvir música."),
    ("restaurante", "餐厅", "o", "compras e lazer", "Local para comer.", "Jantar no restaurante."),
    ("café", "咖啡馆/咖啡", "o", "compras e lazer", "Bebida ou local que a serve.", "Tomar um café."),
    ("bar", "酒吧", "o", "compras e lazer", "Local de bebidas.", "Beber no bar."),
    ("ementa", "菜单", "a", "compras e lazer", "Lista de comida.", "Ver a ementa."),
    ("conta", "账单", "a", "compras e lazer", "Valor a pagar.", "A conta, por favor."),
    ("gorjeta", "小费", "a", "compras e lazer", "Dinheiro extra para o serviço.", "Deixar gorjeta."),
    ("passear", "散步", "v", "compras e lazer", "Andar sem rumo; viajar perto.", "Passear à noite."),
    ("brincar", "玩耍", "v", "compras e lazer", "Entreter-se infantilemente.", "Crianças a brincar."),
    ("correr", "跑步", "v", "compras e lazer", "Andar rápido.", "Correr no parque."),
    ("nadar", "游泳", "v", "compras e lazer", "Mover-se na água.", "Sabe nadar?"),
    ("dançar", "跳舞", "v", "compras e lazer", "Mover ao som da música.", "Dançar bem."),
    ("cantar", "唱歌", "v", "compras e lazer", "Fazer música com a voz.", "Cantar uma canção."),
    ("ler", "阅读", "v", "compras e lazer", "Decifrar texto.", "Ler um livro."),
    ("livro", "书", "o", "compras e lazer", "Conjunto de folhas impressas.", "Lê este livro."),
    ("revista", "杂志", "a", "compras e lazer", "Publicação periódica.", "Comprar uma revista."),
    ("jornal", "报纸", "o", "compras e lazer", "Publicação diária de notícias.", "Ler o jornal."),
    ("televisão", "电视", "a", "compras e lazer", "Aparelho que transmite imagem e som.", "Ver televisão."),
    ("rádio", "收音机/广播", "a/o", "compras e lazer", "Transmissão sonora.", "Ouvir rádio."),
    ("computador", "电脑", "o", "compras e lazer", "Máquina de processamento.", "Jogo no computador."),
    ("jogo", "游戏", "o", "compras e lazer", "Atividade lúdica.", "Jogo de tabuleiro."),
    ("bola", "球", "a", "compras e lazer", "Objeto esférico para jogar.", "Jogar à bola."),
    ("bicicleta", "自行车", "a", "compras e lazer", "Veículo de duas rodas.", "Andar de bicicleta."),
    ("desporto", "运动", "o", "compras e lazer", "Atividade física regrada.", "Fazer desporto."),
    ("futebol", "足球", "o", "compras e lazer", "Desporto popular.", "Jogo de futebol."),
    ("jogar", "玩/打", "v", "compras e lazer", "Praticar um jogo desportivo.", "Jogar ténis."),
    ("equipa", "队伍", "a", "compras e lazer", "Grupo de jogadores.", "Vitória da equipa."),
    ("ganhar", "赢", "v", "compras e lazer", "Sair vitorioso.", "Ganhar o jogo."),
    ("perder", "输", "v", "compras e lazer", "Ficar derrotado.", "Perder o jogo."),
    ("fim de semana", "周末", "o", "compras e lazer", "Sábado e domingo.", "Bom fim de semana."),
    ("férias", "假期", "as", "compras e lazer", "Período de descanso prolongado.", "Boas férias!"),
    ("viagem", "旅行", "a", "compras e lazer", "Ir de um lugar para outro.", "Viagem de avião."),
    ("turista", "游客", "o/a", "compras e lazer", "Pessoa que viaja.", "Grupo de turistas."),
    ("fotografia", "照片", "a", "compras e lazer", "Imagem capturada.", "Tirar fotografia."),
    ("câmara", "相机", "a", "compras e lazer", "Aparelho para fotos.", "Câmara digital."),
    ("tirar", "拍摄/拿走", "v", "compras e lazer", "Fazer uma foto; remover.", "Tirar foto."),
    ("festa", "派对", "a", "compras e lazer", "Celebração convívio.", "Festa de anos."),
    ("bolo", "蛋糕", "o", "compras e lazer", "Doce cozido.", "Bolo de chocolate."),
    ("presente", "礼物", "o", "compras e lazer", "Prenda.", "Abrir o presente."),
    ("prenda", "礼物", "a", "compras e lazer", "Presente, dom.", "Uma linda prenda."),
    ("amigo", "朋友", "o", "compras e lazer", "Pessoa de quem se gosta.", "Querido amigo."),
    ("convidar", "邀请", "v", "compras e lazer", "Pedir para ir.", "Convidar para jantar."),
    ("encontro", "约会/见面", "o", "compras e lazer", "Ato de reunir.", "Temos um encontro hoje."),
    ("óculos", "眼镜", "os", "compras e lazer", "Lentes para ver melhor.", "Pôr os óculos."),
    ("relógio", "手表/钟", "o", "compras e lazer", "Aparelho que mede o tempo.", "Ver o relógio."),
    ("pulseira", "手链", "a", "compras e lazer", "Adorno para o pulso.", "Pulseira de ouro."),
    ("brinco", "耳环", "o", "compras e lazer", "Adorno para as orelhas.", "Lindo brinco."),
    ("anel", "戒指", "o", "compras e lazer", "Adorno para o dedo.", "Anel de prata."),
    ("fio", "项链", "o", "compras e lazer", "Cordão adornado para pescoço.", "Fio bonito."),
    ("carne", "肉", "a", "compras e lazer", "Alimento dos animais.", "Comprar carne."),
    ("peixe", "鱼", "o", "compras e lazer", "Animal do mar, para comer.", "Peixe assado."),
    ("fruta", "水果", "a", "compras e lazer", "Produto das árvores.", "Comer fruta fresca."),
    ("verdura", "蔬菜", "a", "compras e lazer", "Hortaliça.", "Sopa de verdura."),
    ("pão", "面包", "o", "compras e lazer", "Alimento cozido.", "Comprar pão.")
]

A2_WORDS = [
    ("galeria", "画廊/一条街", "a", "compras e lazer", "Corredor ou espaço de arte.", "Visitar a galeria."),
    ("quiosque", "报亭", "o", "compras e lazer", "Pequena loja na rua.", "Comprar no quiosque."),
    ("livraria", "书店", "a", "compras e lazer", "Loja onde se vendem livros.", "Fui à livraria."),
    ("papelaria", "文具店", "a", "compras e lazer", "Loja de papel e escrita.", "Papelaria aberta."),
    ("sapatearia", "鞋店", "a", "compras e lazer", "Loja onde se arranja calçado.", "Perto da sapatearia."),
    ("ourivesaria", "珠宝店", "a", "compras e lazer", "Loja de ouro ou prata.", "Jóias na ourivesaria."),
    ("cliente", "顾客", "o/a", "compras e lazer", "Pessoa que compra.", "Atender o cliente."),
    ("empregado", "员工", "o", "compras e lazer", "Pessoa que trabalha.", "Empregado da loja."),
    ("vendedor", "售货员", "o", "compras e lazer", "Pessoa que vende.", "Bom vendedor."),
    ("montra", "橱窗", "a", "compras e lazer", "Vidraça da loja.", "Ver a montra."),
    ("manequim", "模特(假人)", "o", "compras e lazer", "Boneco para expor roupa.", "Manequim novo."),
    ("provar", "试(吃/穿)", "v", "compras e lazer", "Experimentar algo.", "Provar o prato."),
    ("experimentar", "试", "v", "compras e lazer", "Ensaiar, provar.", "Experimentar sapatos."),
    ("ajustar", "调整/改(衣服)", "v", "compras e lazer", "Pôr justo.", "Ajustar o preço."),
    ("largo", "宽大的/广场", "adj/o", "compras e lazer", "Que não aperta.", "Demasiado largo."),
    ("apertado", "紧的", "adj", "compras e lazer", "Que não tem folga.", "Sapato apertado."),
    ("curto", "短的", "adj", "compras e lazer", "De pouca dimensão.", "Cabelo curto."),
    ("comprido", "长的", "adj", "compras e lazer", "Longo.", "Vestido comprido."),
    ("qualidade", "质量", "a", "compras e lazer", "Grau de excelência.", "Boa qualidade."),
    ("marca", "品牌", "a", "compras e lazer", "Sinal de fabrico.", "Marca famosa."),
    ("garantia", "保修", "a", "compras e lazer", "Segurança de funcionamento.", "Tem garantia."),
    ("defeito", "瑕疵", "o", "compras e lazer", "Falha de fabrico.", "Com defeito."),
    ("trocar", "更换", "v", "compras e lazer", "Permutar.", "Trocar de carro."),
    ("devolver", "退还", "v", "compras e lazer", "Restituir.", "Devolver ao dono."),
    ("reembolso", "退款", "o", "compras e lazer", "Devolução de dinheiro.", "Pedir reembolso."),
    ("saldo", "清仓打折/余额", "o", "compras e lazer", "Desconto de fim de época.", "Em época de saldo."),
    ("liquidação", "清仓", "a", "compras e lazer", "Venda a preço muito baixo.", "Liquidação total."),
    ("cartão de débito", "借记卡", "o", "compras e lazer", "Cartão bancário direto.", "Pagar com cartão de débito."),
    ("cartão de crédito", "信用卡", "o", "compras e lazer", "Cartão bancário com crédito.", "Uso o cartão de crédito."),
    ("transferência", "转账", "a", "compras e lazer", "Passagem de fundos.", "Transferência bancária."),
    ("cheque", "支票", "o", "compras e lazer", "Ordem de pagamento.", "Passar um cheque."),
    ("despesa", "开销", "a", "compras e lazer", "Gasto financeiro.", "Cortar na despesa."),
    ("orçamento", "预算", "o", "compras e lazer", "Cálculo de custos.", "Orçamento apertado."),
    ("poupar", "节省", "v", "compras e lazer", "Não gastar.", "Poupar dinheiro."),
    ("gastar", "花费", "v", "compras e lazer", "Consumir dinheiro.", "Gastar muito."),
    ("bilheteira", "售票处", "a", "compras e lazer", "Local de venda de bilhetes.", "Fila na bilheteira."),
    ("plateia", "观众席", "a", "compras e lazer", "Público ou área do público.", "A plateia aplaudiu."),
    ("balcão", "吧台/柜台", "o", "compras e lazer", "Mesa de atendimento.", "Pagar ao balcão."),
    ("palco", "舞台", "o", "compras e lazer", "Estrado para atuação.", "Estar em palco."),
    ("ator", "男演员", "o", "compras e lazer", "Artista homem.", "O ator principal."),
    ("atriz", "女演员", "a", "compras e lazer", "Artista mulher.", "Uma excelente atriz."),
    ("realizador", "导演", "o", "compras e lazer", "Quem dirige um filme.", "Realizador premiado."),
    ("exposição", "展览", "a", "compras e lazer", "Mostra pública.", "Exposição de arte."),
    ("pintura", "绘画", "a", "compras e lazer", "Arte com tintas.", "Bela pintura."),
    ("quadro", "画", "o", "compras e lazer", "Obra pintada em tela.", "Comprar um quadro."),
    ("escultura", "雕塑", "a", "compras e lazer", "Arte em relevo.", "Arte da escultura."),
    ("arte", "艺术", "a", "compras e lazer", "Criação estética.", "Obra de arte."),
    ("artista", "艺术家", "o/a", "compras e lazer", "Pessoa de dom artístico.", "Grande artista."),
    ("espetáculo", "演出", "o", "compras e lazer", "Apresentação pública.", "Espetáculo incrível."),
    ("festival", "音乐节/节日", "o", "compras e lazer", "Grande evento de música ou cinema.", "Festival de verão."),
    ("banda", "乐队", "a", "compras e lazer", "Grupo musical.", "Ouvir esta banda."),
    ("cantor", "歌手", "o", "compras e lazer", "Quem canta profissionalmente.", "O cantor favorito."),
    ("instrumento", "乐器", "o", "compras e lazer", "Objeto musical.", "Tocar um instrumento."),
    ("guitarra", "吉他", "a", "compras e lazer", "Instrumento de cordas.", "Tocar guitarra portuguesa."),
    ("piano", "钢琴", "o", "compras e lazer", "Instrumento de teclas.", "Aulas de piano."),
    ("passatempo", "爱好", "o", "compras e lazer", "Atividade livre.", "Um bom passatempo."),
    ("coleção", "收藏", "a", "compras e lazer", "Conjunto de objetos da mesma espécie.", "Coleção de selos."),
    ("colecionar", "收集", "v", "compras e lazer", "Reunir objetos.", "Colecionar moedas."),
    ("acampar", "露营", "v", "compras e lazer", "Instalar-se em tendas.", "Acampar na floresta."),
    ("tenda", "帐篷", "a", "compras e lazer", "Abrigo de lona.", "Montar a tenda."),
    ("montanha", "大山", "a", "compras e lazer", "Grande elevação de terreno.", "Passear na montanha."),
    ("neve", "雪", "a", "compras e lazer", "Gelo em flocos.", "Brincar na neve."),
    ("esquiar", "滑雪", "v", "compras e lazer", "Deslizar em esquis.", "Esquiar no inverno."),
    ("surf", "冲浪", "o", "compras e lazer", "Desporto com prancha na onda.", "Fazer surf."),
    ("ginásio", "健身房", "o", "compras e lazer", "Local de exercício.", "Treino no ginásio."),
    ("treinar", "训练", "v", "compras e lazer", "Praticar atividade física.", "Treinar todos os dias."),
    ("campeonato", "锦标赛", "o", "compras e lazer", "Prova desportiva.", "Ganhar o campeonato."),
    ("torneio", "联赛", "o", "compras e lazer", "Competição de vários.", "Torneio internacional."),
    ("estádio", "体育场", "o", "compras e lazer", "Recinto grande desportivo.", "Ir ao estádio."),
    ("campo", "球场/乡下", "o", "compras e lazer", "Local de jogo; natureza.", "Campo de futebol."),
    ("pavilhão", "体育馆", "o", "compras e lazer", "Edifício desportivo fechado.", "Pavilhão polidesportivo."),
    ("claque", "啦啦队/球迷助威团", "a", "compras e lazer", "Grupo de apoiantes.", "A claque apoia."),
    ("árbitro", "裁判", "o", "compras e lazer", "Juiz do jogo.", "O árbitro apitou."),
    ("falta", "犯规/缺点", "a", "compras e lazer", "Ato contra a regra.", "Falta grave."),
    ("golo", "进球", "o", "compras e lazer", "Ponto no futebol.", "Marcar um golo."),
    ("empate", "平局", "o", "compras e lazer", "Igualdade no jogo.", "O jogo deu empate."),
    ("resultado", "比分/结果", "o", "compras e lazer", "Classificação final.", "Bom resultado."),
    ("classificar", "晋级/评级", "v", "compras e lazer", "Atribuir lugar.", "A equipa vai classificar-se."),
    ("vitória", "胜利", "a", "compras e lazer", "Conquista do jogo.", "Vitória fácil."),
    ("derrota", "失败", "a", "compras e lazer", "Perda do jogo.", "Triste derrota."),
    ("esplanada", "露天咖啡座", "a", "compras e lazer", "Local ao ar livre de café.", "Beber na esplanada."),
    ("menu", "菜单", "o", "compras e lazer", "Lista de opções de comida.", "Pedir o menu."),
    ("prato", "盘子/一道菜", "o", "compras e lazer", "Recipiente de comido ou refeição.", "Prato principal."),
    ("sobremesa", "甜点", "a", "compras e lazer", "Doce depois da comida.", "Comer sobremesa."),
    ("gelado", "冰淇淋", "o", "compras e lazer", "Doce gelado.", "Gelado de morango."),
    ("bebida", "饮料", "a", "compras e lazer", "Líquido que se bebe.", "Bebida fresca."),
    ("copo", "杯子", "o", "compras e lazer", "Recipiente para bebida.", "Copo de água."),
    ("garrafa", "瓶子", "a", "compras e lazer", "Recipiente longo.", "Garrafa de vinho."),
    ("pedir", "点菜/请求", "v", "compras e lazer", "Fazer pedido.", "Vou pedir agora."),
    ("servir", "上菜/服务", "v", "compras e lazer", "Prestar serviço.", "Podem servir já."),
    ("delicioso", "美味的", "adj", "compras e lazer", "Muito bom para o paladar.", "Prato delicioso."),
    ("péssimo", "极差的", "adj", "compras e lazer", "Muito mau.", "Serviço péssimo."),
    ("recomendar", "推荐", "v", "compras e lazer", "Aconselhar a.", "O que recomendam?"),
    ("reservar", "预定", "v", "compras e lazer", "Guardar antecipadamente.", "Reservar uma mesa."),
    ("mesa", "桌椅", "a", "compras e lazer", "Móvel de refeição.", "Mesa para dois."),
    ("cadeira", "椅子", "a", "compras e lazer", "Assento com encosto.", "Cadeira confortável."),
    ("toalha", "毛巾/桌布", "a", "compras e lazer", "Pano de mesa ou banho.", "Toalha de praia."),
    ("guarda-sol", "遮阳伞", "o", "compras e lazer", "Abrigo solar de praia.", "Abrir o guarda-sol."),
    ("areia", "沙子", "a", "compras e lazer", "Poeira mineral da praia.", "Castelo de areia."),
    ("onda", "海浪", "a", "compras e lazer", "Movimento da água.", "Onda gigante.")
]

# Helper to load existing vocabulary
def update_json(file_name, new_data, level, category):
    formatted = []
    for w in new_data:
        # Check if example is valid (not empty)
        ex = [{"pt": w[5], "cn": "这是" + w[1] + "的例子。"}] if w[5] else []
        formatted.append({
            "word": w[0],
            "translation": w[1],
            "gender": w[2],
            "cefr_level": level,
            "category": category,
            "priberam_definition": w[4],
            "examples": ex,
            "synonyms": [],
            "antonyms": []
        })
    with open(file_name, "w", encoding="utf-8") as f:
        json.dump(formatted, f, ensure_ascii=False, indent=4)
        
update_json("/Users/caoyicheng/.gemini/antigravity/playground/velvet-equinox/scripts/data_a1_c3.json", A1_WORDS, "A1", "compras e lazer")
update_json("/Users/caoyicheng/.gemini/antigravity/playground/velvet-equinox/scripts/data_a2_c3.json", A2_WORDS, "A2", "compras e lazer")
print("A1 and A2 generated")
