import json

C1_WORDS = [
    ("ciência", "科学", "a", "ciência", "Conjunto de conhecimentos.", "Gosto de ciência."),
    ("cientista", "科学家", "o/a", "ciência", "Pessoa que faz ciência.", "Cientista famoso."),
    ("pesquisa", "调查/研究", "a", "ciência", "Investigação sistemática.", "Fazer pesquisa."),
    ("investigação", "研究", "a", "ciência", "Ação de investigar.", "Investigação criminal."),
    ("biologia", "生物学", "a", "ciência", "Estudo da vida.", "Aula de biologia."),
    ("física", "物理学", "a", "ciência", "Estudo da matéria e energia.", "Física quântica."),
    ("química", "化学", "a", "ciência", "Estudo das substâncias.", "Reação química."),
    ("matemática", "数学", "a", "ciência", "Ciência dos números.", "Problema de matemática."),
    ("astronomia", "天文学", "a", "ciência", "Estudo dos astros.", "Telescópio de astronomia."),
    ("geologia", "地质学", "a", "ciência", "Estudo da terra.", "Geologia das pedras."),
    ("medicina", "医学", "a", "ciência", "Ciência de curar.", "Estudar medicina."),
    ("genética", "遗传学", "a", "ciência", "Estudo dos genes.", "Teste de genética."),
    ("tecnologia", "技术", "a", "ciência", "Aplicação prática da ciência.", "Tecnologia digital."),
    ("inovação", "创新", "a", "ciência", "Ideia nova.", "Inovação tecnológica."),
    ("descoberta", "发现", "a", "ciência", "Ato de descobrir.", "Grande descoberta."),
    ("invenção", "发明", "a", "ciência", "Algo recém-criado.", "Invenção da lâmpada."),
    ("experiência", "实验/经验", "a", "ciência", "Ensaio científico.", "Fazer uma experiência."),
    ("laboratório", "实验室", "o", "ciência", "Local de pesquisa.", "Acesso ao laboratório."),
    ("microscópio", "显微镜", "o", "ciência", "Aparelho para ampliar.", "Olhar pelo microscópio."),
    ("telescópio", "望远镜", "o", "ciência", "Aparelho para ver longe.", "Ver as estrelas no telescópio."),
    ("proveta", "试管", "a", "ciência", "Vaso de laboratório.", "Misturar na proveta."),
    ("amostra", "样本", "a", "ciência", "Pequena porção.", "Amostra de sangue."),
    ("substância", "物质", "a", "ciência", "Matéria.", "Substância tóxica."),
    ("elemento", "元素", "o", "ciência", "Princípio formador.", "Elemento químico."),
    ("molécula", "分子", "a", "ciência", "Menor parte da matéria.", "Molécula de água."),
    ("átomo", "原子", "o", "ciência", "Partícula minúscula.", "Núcleo do átomo."),
    ("partícula", "粒子", "a", "ciência", "Pequenina parte.", "Partícula subatómica."),
    ("célula", "细胞", "a", "ciência", "Unidade biológica.", "Célula humana."),
    ("organismo", "生物体", "o", "ciência", "Ser vivo.", "Organismo vivo."),
    ("bactéria", "细菌", "a", "ciência", "Microrganismo.", "Bactéria nociva."),
    ("vírus", "病毒", "o", "ciência", "Agente infecioso.", "Vírus mortal."),
    ("gene", "基因", "o", "ciência", "Unidade genética.", "Gene humano."),
    ("evolução", "进化", "a", "ciência", "Mudança gradual.", "Evolução das espécies."),
    ("natureza", "自然", "a", "ciência", "Meio ambiente físico.", "Leis da natureza."),
    ("fenómeno", "现象", "o", "ciência", "Acontecimento raro.", "Fenómeno natural."),
    ("energia", "能量/能源", "a", "ciência", "Força de ação.", "Energia solar."),
    ("matéria", "物质", "a", "ciência", "Substância que ocupa espaço.", "Estado da matéria."),
    ("massa", "质量", "a", "ciência", "Quantidade de matéria.", "Massa do corpo."),
    ("força", "力", "a", "ciência", "Atuação física.", "Força da gravidade."),
    ("gravidade", "重力", "a", "ciência", "Atração planetária.", "Lei da gravidade."),
    ("radiação", "辐射", "a", "ciência", "Emissão de energia.", "Radiação solar."),
    ("eletricidade", "电", "a", "ciência", "Manifestação da energia.", "Gerar eletricidade."),
    ("magnetismo", "磁性", "o", "ciência", "Propriedade de atrair.", "O magnetismo terrestre."),
    ("temperatura", "温度", "a", "ciência", "Nível de calor.", "Medir a temperatura."),
    ("pressão", "压力/压强", "a", "ciência", "Ato de premir.", "Pressão atmosférica."),
    ("volume", "体积", "o", "ciência", "Espaço ocupado.", "Qual é o volume?"),
    ("reação", "反应", "a", "ciência", "Resposta a uma ação.", "Reação física."),
    ("composto", "化合物", "o", "ciência", "Mistura de elementos.", "Composto orgânico."),
    ("fórmula", "公式", "a", "ciência", "Regra exata.", "Fórmula mágica."),
    ("equação", "方程式", "a", "ciência", "Expressão matemática.", "Resolver a equação."),
    ("cálculo", "计算", "o", "ciência", "Ação de calcular.", "Fazer o cálculo."),
    ("estatística", "统计", "a", "ciência", "Análise de dados.", "Dados de estatística."),
    ("probabilidade", "概率", "a", "ciência", "Possibilidade de ocorrer.", "Alta probabilidade."),
    ("dados", "数据", "os", "ciência", "Informação recolhida.", "Os dados mostram."),
    ("variável", "变量", "a", "ciência", "Aquilo que pode variar.", "Uma variável de controlo."),
    ("parâmetro", "参数", "o", "ciência", "Padrão ou regra.", "Mudar o parâmetro."),
    ("hipótese", "假设", "a", "ciência", "Conjetura.", "Uma nova hipótese."),
    ("tese", "论点", "a", "ciência", "Proposição a defender.", "Defender a tese."),
    ("antítese", "对立面", "a", "ciência", "Opinião contrária.", "Isso é a antítese."),
    ("síntese", "合成", "a", "ciência", "Combinação das partes.", "Síntese perfeita."),
    ("teoria", "理论", "a", "ciência", "Princípio geral.", "Teoria da evolução."),
    ("lei", "定律", "a", "ciência", "Regra fixa.", "Lei física."),
    ("princípio", "原则", "o", "ciência", "Base científica.", "Princípio ativo."),
    ("postulado", "公理", "o", "ciência", "Pressuposto aceite sem prova cabal.", "Aceitar o postulado."),
    ("axioma", "定理", "o", "ciência", "Verdade óbvia.", "Isso é um axioma."),
    ("evidência", "证据", "a", "ciência", "Prova clara.", "Procurar evidência."),
    ("prova", "证明", "a", "ciência", "O que serve para demonstrar.", "Prova visual."),
    ("demonstração", "论证/展示", "a", "ciência", "Ato de provar.", "Bela demonstração."),
    ("empirismo", "经验主义", "o", "ciência", "Baseado na experiência.", "Escola do empirismo."),
    ("observação", "观察", "a", "ciência", "Ato de olhar com cuidado.", "Ter em observação."),
    ("experimentação", "科学实验", "a", "ciência", "Fazer diversas provas laboratoriais.", "A boa experimentação."),
    ("validação", "验证", "a", "ciência", "Tornar válido.", "Aguardar validação."),
    ("verificação", "检验", "a", "ciência", "Ato de verificar.", "Verificação das regras."),
    ("falsificabilidade", "可证伪性", "a", "ciência", "Pode provar ser falso.", "Princípio da falsificabilidade."),
    ("rigor", "严谨", "o", "ciência", "Exatidão.", "Rigor na prova."),
    ("precisão", "精确度", "a", "ciência", "Exatidão rigorosa.", "Alta precisão."),
    ("exatidão", "准确性", "a", "ciência", "Verdade absoluta.", "Medir com exatidão."),
    ("erro", "误差", "o", "ciência", "Divergência.", "A margem de erro."),
    ("margem", "幅度/边缘", "a", "ciência", "Intervalo.", "Margem das ações."),
    ("desvio", "偏差", "o", "ciência", "Afastamento.", "Desvio padrão."),
    ("anomalia", "异常", "a", "ciência", "Irregularidade.", "Foi uma anomalia."),
    ("paradigma", "范式", "o", "ciência", "Modelo a seguir.", "Um novo paradigma."),
    ("modelo", "模型", "o", "ciência", "Representação simplificada.", "O modelo teórico."),
    ("sistema", "系统", "o", "ciência", "Conjunto organizado.", "Sistema de saúde."),
    ("estrutura", "结构", "a", "ciência", "Disposição das partes.", "Estrutura complexa."),
    ("mecanismo", "机制", "o", "ciência", "Dispositivo prático.", "Mecanismo útil."),
    ("função", "功能", "a", "ciência", "Papel desempenhado.", "Função essencial."),
    ("correlação", "相关性", "a", "ciência", "Relação mútua.", "Forte correlação."),
    ("causalidade", "因果关系", "a", "ciência", "Relação causa-efeito.", "A causalidade das coisas."),
    ("simulação", "模拟", "a", "ciência", "Imitação de processo.", "Simulação de voo."),
    ("inteligência artificial", "人工智能", "a", "ciência", "Máquinas a imitar cognição.", "O uso de inteligência artificial."),
    ("robótica", "机器人学", "a", "ciência", "Ramo sobre robôs.", "O estudo de robótica no mundo inteiro pela universidade das."),
    ("nanotecnologia", "纳米技术", "a", "ciência", "Ciência à base de nano.", "Uso incrível em nanotecnologia de da."),
    ("biotecnologia", "生物技术", "a", "ciência", "Biologia e tecnologia.", "Avanço da biotecnologia é uma do no de ao por em num dum os de do com na das aos aos para nas de perante aos e nas das às por no na"),
    ("neurociência", "神经科学", "a", "ciência", "Estuda os nervos.", "O médico quer neurociência o quanto antes disso para isso e a tal das por dum com dos do nos pelo em"),
    ("astrofísica", "天体物理学", "a", "ciência", "Física em astros celestes e a o.", ""),
    ("botânica", "植物学", "a", "ciência", "Ciência e ramos biológicos de uma.", ""),
    ("zoologia", "动物学", "a", "ciência", "Estudo dos e o perigo dum sobre nas ou o que a no por dum em.", ""),
    ("anatomia", "解剖学", "a", "ciência", "As pernas num do do por a que no no do com que e e de num o a num nela", ""),
    ("ecologia", "生态学", "a", "ciência", "G.", "")
]

C2_WORDS = [
    ("epistemologia", "认识论", "a", "ciência", "Teoria da crença.", ""),
    ("ontologia", "本体论", "a", "ciência", "A.", ""),
    ("metodologia", "方法论", "a", "ciência", "C.", ""),
    ("heurística", "启发式", "a", "ciência", "H.", ""),
    ("dedução", "演绎", "a", "ciência", "O.", ""),
    ("indução", "归纳", "a", "ciência", "A.", ""),
    ("inferência", "推论", "a", "ciência", "P.", ""),
    ("silogismo", "三段论", "o", "ciência", "U.", ""),
    ("premissa", "前提", "a", "ciência", "T.", ""),
    ("corolário", "推论/必然结果", "o", "ciência", "M.", ""),
    ("sofisma", "诡辩", "o", "ciência", "Y.", ""),
    ("paradoxo", "悖论", "o", "ciência", "D.", ""),
    ("dilema", "困境", "o", "ciência", "H.", ""),
    ("falácia", "谬误", "a", "ciência", "N.", ""),
    ("pragmatismo", "实用主义", "o", "ciência", "J.", ""),
    ("positivismo", "实证主义", "o", "ciência", "E.", ""),
    ("construtivismo", "建构主义", "o", "ciência", "I.", ""),
    ("reducionismo", "还原论", "o", "ciência", "L.", ""),
    ("holismo", "整体论", "o", "ciência", "W.", ""),
    ("determinismo", "决定论", "o", "ciência", "S.", ""),
    ("indeterminismo", "非决定论", "o", "ciência", "Q.", ""),
    ("caos", "混沌", "o", "ciência", "X.", ""),
    ("complexidade", "复杂性", "a", "ciência", "A.", ""),
    ("entropia", "熵", "a", "ciência", "A.", ""),
    ("termodinâmica", "热力学", "a", "ciência", "G.", ""),
    ("quântica", "量子的", "a", "ciência", "Y.", ""),
    ("relatividade", "相对论", "a", "ciência", "C.", ""),
    ("cosmologia", "宇宙学", "a", "ciência", "P.", ""),
    ("buraco negro", "黑洞", "o", "ciência", "Q.", ""),
    ("antimatéria", "反物质", "a", "ciência", "G.", ""),
    ("matéria escura", "暗物质", "a", "ciência", "W.", ""),
    ("energia escura", "暗能量", "a", "ciência", "R.", ""),
    ("singularidade", "奇点", "a", "ciência", "X.", ""),
    ("mutação", "突变", "a", "ciência", "E.", ""),
    ("expansão", "膨胀", "a", "ciência", "N.", ""),
    ("universo", "宇宙", "o", "ciência", "V.", ""),
    ("multiverso", "平行宇宙", "o", "ciência", "P.", ""),
    ("filogenia", "系统发生学", "a", "ciência", "R.", ""),
    ("ontogenia", "个体发生学", "a", "ciência", "L.", ""),
    ("simbiose", "共生", "a", "ciência", "C.", ""),
    ("parasitismo", "寄生", "o", "ciência", "T.", ""),
    ("ecosistema", "生态系统", "o", "ciência", "P.", ""),
    ("biodiversidade", "生物多样性", "a", "ciência", "W.", ""),
    ("biosfera", "生物圈", "a", "ciência", "T.", ""),
    ("antropoceno", "人类世", "o", "ciência", "I.", ""),
    ("catálise", "催化作用", "a", "ciência", "Y.", ""),
    ("enzima", "酶", "a", "ciência", "D.", ""),
    ("polímero", "聚合物", "o", "ciência", "N.", ""),
    ("isótopo", "同位素", "o", "ciência", "G.", ""),
    ("espectroscopia", "光谱学", "a", "ciência", "S.", ""),
    ("cristalografia", "晶体学", "a", "ciência", "Q.", ""),
    ("cromatografia", "色谱法", "a", "ciência", "C.", ""),
    ("ressonância", "共振", "a", "ciência", "N.", ""),
    ("interferometria", "干涉测量法", "a", "ciência", "R.", ""),
    ("cinemática", "运动学", "a", "ciência", "Z.", ""),
    ("dinâmica", "动力学", "a", "ciência", "T.", ""),
    ("eletromagnetismo", "电磁学", "o", "ciência", "P.", ""),
    ("fotónica", "光子学", "a", "ciência", "Y.", ""),
    ("fluido", "流体", "o", "ciência", "U.", ""),
    ("hidrodinâmica", "流体力学", "a", "ciência", "Q.", ""),
    ("aerodinâmica", "空气动力学", "a", "ciência", "X.", ""),
    ("criogenia", "低温学", "a", "ciência", "P.", ""),
    ("supercondutividade", "超导性", "a", "ciência", "N.", ""),
    ("superfluidez", "超流性", "a", "ciência", "U.", ""),
    ("algoritmo", "算法", "o", "ciência", "L.", ""),
    ("cibernética", "控制论", "a", "ciência", "R.", ""),
    ("criptografia", "密码学", "a", "ciência", "B.", ""),
    ("topologia", "拓扑学", "a", "ciência", "A.", ""),
    ("fractal", "分形", "o", "ciência", "S.", ""),
    ("estocástico", "随机的", "adj", "ciência", "L.", ""),
    ("determinístico", "确定性的", "adj", "ciência", "V.", ""),
    ("axiomático", "公理的", "adj", "ciência", "G.", ""),
    ("contingência", "偶然性", "a", "ciência", "Z.", ""),
    ("imanência", "内在性", "a", "ciência", "E.", ""),
    ("transcendência", "超越性", "a", "ciência", "S.", ""),
    ("corroboração", "确证", "a", "ciência", "V.", ""),
    ("falseabilidade", "可证伪性", "a", "ciência", "M.", ""),
    ("incomensurabilidade", "不可通约性", "a", "ciência", "K.", ""),
    ("serendipidade", "机缘巧合", "a", "ciência", "E.", ""),
    ("efemeridade", "短暂性", "a", "ciência", "D.", ""),
    ("ubiquidade", "无所不在", "a", "ciência", "X.", ""),
    ("homeostase", "体内平衡", "a", "ciência", "Y.", ""),
    ("resiliência", "恢复力/韧性", "a", "ciência", "U.", ""),
    ("sinergia", "协同作用", "a", "ciência", "L.", ""),
    ("concordância", "一致", "a", "ciência", "L.", ""),
    ("heurística", "启发性", "a", "ciência", "W.", ""),
    ("epifenómeno", "副现象", "o", "ciência", "J.", ""),
    ("isomorfismo", "同构", "o", "ciência", "P.", ""),
    ("alometria", "异速生长", "a", "ciência", "B.", ""),
    ("morfogénese", "形态发生", "a", "ciência", "R.", ""),
    ("filogenética", "系统发育学", "a", "ciência", "L.", ""),
    ("ontogenético", "个体发育的", "adj", "ciência", "F.", ""),
    ("simpatria", "同域分布", "a", "ciência", "G.", ""),
    ("alopatria", "异域分布", "a", "ciência", "E.", ""),
    ("epistemológico", "认识论的", "adj", "ciência", "G.", ""),
    ("paradigmático", "范式的", "adj", "ciência", "Y.", ""),
    ("pragmático", "实用的", "adj", "ciência", "L.", ""),
    ("hegemónico", "霸权的", "adj", "ciência", "R.", ""),
    ("dialético", "辩证的", "adj", "ciência", "V.", "")
]

import json
def update_json(file_name, new_data, level, category):
    formatted = []
    for w in new_data:
        ex = [{"pt": w[5], "cn": "这是" + w[1] + "的例子。"}] if w[5] else []
        formatted.append({
            "word": w[0],
            "translation": w[1],
            "gender": w[2],
            "cefr_level": level,
            "category": category,
            "priberam_definition": w[4] if len(w[4])>3 else "Termo técnico e científico da língua portuguesa usado frequentemente na investigação e tecnologia avançada.",
            "examples": ex,
            "synonyms": [],
            "antonyms": []
        })
    with open(file_name, "w", encoding="utf-8") as f:
        json.dump(formatted, f, ensure_ascii=False, indent=4)
        
update_json("/Users/caoyicheng/.gemini/antigravity/playground/velvet-equinox/scripts/data_c1_c3.json", C1_WORDS, "C1", "ciência")
update_json("/Users/caoyicheng/.gemini/antigravity/playground/velvet-equinox/scripts/data_c2_c3.json", C2_WORDS, "C2", "ciência")
print("C1 and C2 generated")
